//
//  LoginPresenter.swift
//  TMDBViewer
//
//  Created by Gabriel Targon on 22/10/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentHome()
    func presentError(description: String)
}

class LoginPresenter: LoginPresentationLogic {
    weak var viewController: LoginDisplayLogic?
    
    func presentHome() {
        viewController?.displayHome()
    }
    
    func presentError(description: String) {
        viewController?.displayError(description: description)
    }
}
