//
//  LoginWorker.swift
//  TMDBViewer
//
//  Created by Gabriel Targon on 22/10/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class LoginWorker {
    
    func fetchLogin(with credentials: Login.User.Request,
                    result: @escaping (Result<Bool, NetworkError>) -> Void) {
        getRequestToken { response in
            switch response {
            case .success(let data):
                var endpoint = TMDBEndpoint(path: "authentication/token/validate_with_login",
                                            method: .post)
                endpoint.parameters = ["username" : credentials.username,
                                       "password" : credentials.password,
                                       "request_token" : data.requestToken]
                
                NetworkService.makeRequest(endpoint) { (response: Result<Login.SessionResponse, NetworkError>) in
                    switch response {
                    case .success(let data):
                        result(.success(data.success))
                    case.failure(let error):
                        result(.failure(error))
                    }
                }
            case.failure:
                result(.failure(.decodeError))
            }
        }
    }
    
    func getRequestToken(result: @escaping (Result<Login.TokenRequest, Error>) -> Void) {
        let endpoint = TMDBEndpoint(path: "authentication/token/new",
                                    method: .get)
        
        NetworkService.makeRequest(endpoint) { (response: Result<Login.TokenRequest, NetworkError>) in
            switch response {
            case .success(let data):
                result(.success(data))
            case.failure(let error):
                result(.failure(error))
            }
        }
    }
}
