//
//  DetailWorker.swift
//  TMDBViewer
//
//  Created by Gabriel Targon on 20/10/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class DetailWorker {
    
    func fetchMovie(id: Int,
                    result: @escaping (Result<Movie, NetworkError>) -> Void) {
        
        var endpoint = TMDBEndpoint(path: "movie/\(id)",
                                    method: .get)
        endpoint.parameters = ["append_to_response" : "credits"]
        
        NetworkService.makeRequest(endpoint) { (response: Result<Movie, NetworkError>) in
            switch response {
            case .success(let data):
                result(.success(data))
            case.failure(let error):
                result(.failure(error))
            }
        }
    }
}
