//
//  DetailRouter.swift
//  TMDBViewer
//
//  Created by Gabriel Targon on 20/10/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailRoutingLogic {
    func routeToError(description: String)
}

protocol DetailDataPassing {
    var dataStore: DetailDataStore? { get }
}

class DetailRouter: NSObject, DetailRoutingLogic, DetailDataPassing {
    weak var viewController: UIViewController?
    var dataStore: DetailDataStore?
    
    func routeToError(description: String) {
        DispatchQueue.main.async {
            let alert = UIAlertController(title: "Something went wrong",
                                          message: description,
                                          preferredStyle: .alert)
            
            alert.addAction(UIAlertAction(title: "Close",
                                          style: .default,
                                          handler: nil))
            
            self.viewController?.present(alert, animated: true, completion: nil)
        }
    }
}
