//
//  DetailPresenter.swift
//  TMDBViewer
//
//  Created by Gabriel Targon on 20/10/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentMovie(response: Detail.Film.Response)
    func presentError(description: String)
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?
    
    // MARK: Present functions
    
    func presentMovie(response: Detail.Film.Response) {
        let movie = response.movie
        let viewModel = Detail.Film.ViewModel(id: movie.id,
                                              backdropImageURL: movie.backdropURL,
                                              title: movie.title,
                                              rate: String(format: "%.1f", movie.voteAverage),
                                              date: movie.releaseDate.getFormattedDate(format: "d MMMM yyyy"),
                                              description: movie.overview,
                                              genres: movie.genres,
                                              cast: movie.credits)
        viewController?.displayMovieInfo(viewModel: viewModel)
    }
    
    func presentError(description: String) {
        viewController?.displayError(description: description)
    }
}
