//
//  HomeInteractor.swift
//  TMDBViewer
//
//  Created by Gabriel Targon on 19/10/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func requestMoviesList(request: Home.Movies.Request)
}

protocol HomeDataStore {}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker: HomeWorker = HomeWorker()
    
    // MARK: Requests
    
    func requestMoviesList(request: Home.Movies.Request) {
        worker.fetchMovies(endpoint: request.endpoint) { [weak self] result in
            switch result {
            case .success(let response):
                let response = Home.Movies.Response(movies: response)
                self?.presenter?.presentMovies(response: response)
            case .failure(let error):
                self?.presenter?.presentError(description: error.localizedDescription)
            }
        }
        
        
    }
}
