//
//  HomeModels.swift
//  TMDBViewer
//
//  Created by Gabriel Targon on 19/10/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: Use cases
    
    enum Movies {
        struct Request {
            let endpoint: Endpoint
        }
        
        struct Response {
            let movies: MoviesResponse
        }
        
        struct ViewModel {
            var movies: [Movie]
        }
    }
    
    struct Movie {
        var id: Int
        var image: URL
        var title: String
        var date: String
        var rating: String
        var description: String
    }
    
    enum Endpoint: String, CaseIterable {
        case nowPlaying = "now_playing"
        case upcoming
        case popular
        case topRated = "top_rated"
    }
}
